### ISSUE TITLE
Clubhouse API V2

### ISSUE THREAD

**Issue by camilleacey** [LearnersGuild/github-clubhouse#15]
I just wanted to let you know that we've released [Clubhouse V2](https://clubhouse.io/api/rest/v2/). While V1 will continue to be supported, V2 exposes endpoints for several new features such as Teams, Milestones, and Categories.

**Comment by jeffreywescott** [comment]
Thanks, @camilleacey ... to be honest, we haven't been using Clubhouse lately; it might be good to find this project a new maintainer.
